[capabilities.stdio.println]
enabled = true

[capabilities.github.issue.create]
enabled = true
allowed_repos = ["vectorian-rs/hiko"]

[capabilities.github.issue.view]
enabled = true
allowed_repos = ["vectorian-rs/hiko"]

[capabilities.github.issue.update]
enabled = true
allowed_repos = ["vectorian-rs/hiko"]
