[capabilities.stdio.println]
enabled = true

[capabilities.convert.string_to_int]
enabled = true

[capabilities.string.split]
enabled = true

[capabilities.string.string_contains]
enabled = true

[capabilities.testing.panic]
enabled = true

[capabilities.github.issue.create]
enabled = true
allowed_repos = ["vectorian-rs/hiko"]

[capabilities.github.issue.view]
enabled = true
allowed_repos = ["vectorian-rs/hiko"]

[capabilities.github.issue.update]
enabled = true
allowed_repos = ["vectorian-rs/hiko"]
